_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.9.18
        t:
            "1":
                - 1
                - 41
                - 51
                - 55
            "2":
                - 1
                - 41
                - 51
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.18
            "5": 0.18.6
            "8":
                - 5
            "12": 0.18.6
            "13": linux-x86_64
architecture:
    value: SpectrVelCNNRegr
batch_size:
    value: 10
dataset:
    value: SpectrogramDataset
epochs:
    value: 300
learning_rate:
    value: 1e-05
loss_fn:
    value: mse_loss
nfft:
    value: 512
optimizer:
    value: SGD
transform:
    value: LoadSpectrogram|Prepro|ToTensor|InterpolateSpectrogram
